// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: sochitiettaikhoan.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SoChiTietTaiKhoanRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID DA SWAP theo quy uoc SQL Server <-> ClickHouse.
	// Viec swap do Java lam (SqlServerUuidSwap); Go chi nhan UUID chuan.
	CompanyIds       []string `protobuf:"bytes,1,rep,name=company_ids,json=companyIds,proto3" json:"company_ids,omitempty"`
	PrimaryCompanyId string   `protobuf:"bytes,2,opt,name=primary_company_id,json=primaryCompanyId,proto3" json:"primary_company_id,omitempty"`
	AccountNumbers   []string `protobuf:"bytes,3,rep,name=account_numbers,json=accountNumbers,proto3" json:"account_numbers,omitempty"`
	FromDate         string   `protobuf:"bytes,4,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"` // YYYY-MM-DD
	ToDate           string   `protobuf:"bytes,5,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`       // YYYY-MM-DD
	// "TH" = tat ca loai tien; nguoc lai loc theo ma.
	CurrencyId string `protobuf:"bytes,6,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`
	// 1 = so tai chinh (type_ledger 0, cot no_fbook)
	// 0 = so quan tri  (type_ledger 1, cot no_mbook)
	IsFinancialBook int32 `protobuf:"varint,7,opt,name=is_financial_book,json=isFinancialBook,proto3" json:"is_financial_book,omitempty"`
	// 1 = gop ca don vi phu thuoc (bridge_org_scope)
	IsDependent int32 `protobuf:"varint,8,opt,name=is_dependent,json=isDependent,proto3" json:"is_dependent,omitempty"`
	// 1 = cong gop but toan cung (account, reference, date, no, corr)
	GroupSameItem int32 `protobuf:"varint,9,opt,name=group_same_item,json=groupSameItem,proto3" json:"group_same_item,omitempty"`
	// true = expand xuong toan bo tai khoan con qua bridge_account_hierarchy
	IsParentNode bool `protobuf:"varint,10,opt,name=is_parent_node,json=isParentNode,proto3" json:"is_parent_node,omitempty"`
	// Multi-cluster. Rong = khong loc.
	ClusterId     string `protobuf:"bytes,11,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SoChiTietTaiKhoanRequest) Reset() {
	*x = SoChiTietTaiKhoanRequest{}
	mi := &file_sochitiettaikhoan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SoChiTietTaiKhoanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoChiTietTaiKhoanRequest) ProtoMessage() {}

func (x *SoChiTietTaiKhoanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sochitiettaikhoan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoChiTietTaiKhoanRequest.ProtoReflect.Descriptor instead.
func (*SoChiTietTaiKhoanRequest) Descriptor() ([]byte, []int) {
	return file_sochitiettaikhoan_proto_rawDescGZIP(), []int{0}
}

func (x *SoChiTietTaiKhoanRequest) GetCompanyIds() []string {
	if x != nil {
		return x.CompanyIds
	}
	return nil
}

func (x *SoChiTietTaiKhoanRequest) GetPrimaryCompanyId() string {
	if x != nil {
		return x.PrimaryCompanyId
	}
	return ""
}

func (x *SoChiTietTaiKhoanRequest) GetAccountNumbers() []string {
	if x != nil {
		return x.AccountNumbers
	}
	return nil
}

func (x *SoChiTietTaiKhoanRequest) GetFromDate() string {
	if x != nil {
		return x.FromDate
	}
	return ""
}

func (x *SoChiTietTaiKhoanRequest) GetToDate() string {
	if x != nil {
		return x.ToDate
	}
	return ""
}

func (x *SoChiTietTaiKhoanRequest) GetCurrencyId() string {
	if x != nil {
		return x.CurrencyId
	}
	return ""
}

func (x *SoChiTietTaiKhoanRequest) GetIsFinancialBook() int32 {
	if x != nil {
		return x.IsFinancialBook
	}
	return 0
}

func (x *SoChiTietTaiKhoanRequest) GetIsDependent() int32 {
	if x != nil {
		return x.IsDependent
	}
	return 0
}

func (x *SoChiTietTaiKhoanRequest) GetGroupSameItem() int32 {
	if x != nil {
		return x.GroupSameItem
	}
	return 0
}

func (x *SoChiTietTaiKhoanRequest) GetIsParentNode() bool {
	if x != nil {
		return x.IsParentNode
	}
	return false
}

func (x *SoChiTietTaiKhoanRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

// Mot dong cua so chi tiet. Anh xa 1-1 voi SoChiTietTaiKhoanDTO ben Java.
type SoChiTietTaiKhoanRow struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 0 = So du dau ky | 1 = Chi tiet | 2 = Cong phat sinh | 3 = So du cuoi ky
	OrderType            int32  `protobuf:"varint,1,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`
	OrderNumber          int32  `protobuf:"varint,2,opt,name=order_number,json=orderNumber,proto3" json:"order_number,omitempty"`
	Bold                 bool   `protobuf:"varint,3,opt,name=bold,proto3" json:"bold,omitempty"`
	AccountNumber        string `protobuf:"bytes,4,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	AccountCategoryKind  int32  `protobuf:"varint,5,opt,name=account_category_kind,json=accountCategoryKind,proto3" json:"account_category_kind,omitempty"` // 0 du No | 1 du Co | 2 luong tinh
	KeyId                string `protobuf:"bytes,6,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	ReferenceId          string `protobuf:"bytes,7,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"` // UUID, rong neu khong co
	TypeId               int32  `protobuf:"varint,8,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	PostedDate           string `protobuf:"bytes,9,opt,name=posted_date,json=postedDate,proto3" json:"posted_date,omitempty"` // RFC3339, rong neu null
	InvoiceDate          string `protobuf:"bytes,10,opt,name=invoice_date,json=invoiceDate,proto3" json:"invoice_date,omitempty"`
	InvoiceNo            string `protobuf:"bytes,11,opt,name=invoice_no,json=invoiceNo,proto3" json:"invoice_no,omitempty"`
	No                   string `protobuf:"bytes,12,opt,name=no,proto3" json:"no,omitempty"` // no_fbook hoac no_mbook tuy loai so
	Reason               string `protobuf:"bytes,13,opt,name=reason,proto3" json:"reason,omitempty"`
	JournalMemo          string `protobuf:"bytes,14,opt,name=journal_memo,json=journalMemo,proto3" json:"journal_memo,omitempty"`
	AccountCorresponding string `protobuf:"bytes,15,opt,name=account_corresponding,json=accountCorresponding,proto3" json:"account_corresponding,omitempty"`
	// ── TIEN TE ──────────────────────────────────────────────────────────────
	// Dung STRING, KHONG dung double.
	// Nguon la Decimal(25,10) - 25 chu so vuot xa do chinh xac cua double
	// (~15-17 chu so). Qua double se sai phan le, ma voi so ke toan thi lech
	// mot dong cung la loi. Java parse lai bang new BigDecimal(s).
	DebitAmount                 string `protobuf:"bytes,16,opt,name=debit_amount,json=debitAmount,proto3" json:"debit_amount,omitempty"`
	CreditAmount                string `protobuf:"bytes,17,opt,name=credit_amount,json=creditAmount,proto3" json:"credit_amount,omitempty"`
	DebitAmountOriginal         string `protobuf:"bytes,18,opt,name=debit_amount_original,json=debitAmountOriginal,proto3" json:"debit_amount_original,omitempty"`
	CreditAmountOriginal        string `protobuf:"bytes,19,opt,name=credit_amount_original,json=creditAmountOriginal,proto3" json:"credit_amount_original,omitempty"`
	ClosingDebitAmount          string `protobuf:"bytes,20,opt,name=closing_debit_amount,json=closingDebitAmount,proto3" json:"closing_debit_amount,omitempty"`
	ClosingCreditAmount         string `protobuf:"bytes,21,opt,name=closing_credit_amount,json=closingCreditAmount,proto3" json:"closing_credit_amount,omitempty"`
	ClosingDebitAmountOriginal  string `protobuf:"bytes,22,opt,name=closing_debit_amount_original,json=closingDebitAmountOriginal,proto3" json:"closing_debit_amount_original,omitempty"`
	ClosingCreditAmountOriginal string `protobuf:"bytes,23,opt,name=closing_credit_amount_original,json=closingCreditAmountOriginal,proto3" json:"closing_credit_amount_original,omitempty"`
	ExchangeRate                string `protobuf:"bytes,24,opt,name=exchange_rate,json=exchangeRate,proto3" json:"exchange_rate,omitempty"`
	OrderPriority               int32  `protobuf:"varint,25,opt,name=order_priority,json=orderPriority,proto3" json:"order_priority,omitempty"`
	IsUnreasonableCost          string `protobuf:"bytes,26,opt,name=is_unreasonable_cost,json=isUnreasonableCost,proto3" json:"is_unreasonable_cost,omitempty"`
	AccountingObjectCode        string `protobuf:"bytes,27,opt,name=accounting_object_code,json=accountingObjectCode,proto3" json:"accounting_object_code,omitempty"`
	AccountingObjectName        string `protobuf:"bytes,28,opt,name=accounting_object_name,json=accountingObjectName,proto3" json:"accounting_object_name,omitempty"`
	// Luon dung 5 phan tu, index 0..4.
	CustomField       []string `protobuf:"bytes,29,rep,name=custom_field,json=customField,proto3" json:"custom_field,omitempty"`
	CustomFieldDetail []string `protobuf:"bytes,30,rep,name=custom_field_detail,json=customFieldDetail,proto3" json:"custom_field_detail,omitempty"`
	// Chuoi "154 - Chi phi SXKD do dang". Frontend dung cho dong tieu de nhom
	// khi nguoi dung chon xem "Tat ca" tai khoan.
	AccountNameWithAccountNumber string `protobuf:"bytes,31,opt,name=account_name_with_account_number,json=accountNameWithAccountNumber,proto3" json:"account_name_with_account_number,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *SoChiTietTaiKhoanRow) Reset() {
	*x = SoChiTietTaiKhoanRow{}
	mi := &file_sochitiettaikhoan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SoChiTietTaiKhoanRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoChiTietTaiKhoanRow) ProtoMessage() {}

func (x *SoChiTietTaiKhoanRow) ProtoReflect() protoreflect.Message {
	mi := &file_sochitiettaikhoan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoChiTietTaiKhoanRow.ProtoReflect.Descriptor instead.
func (*SoChiTietTaiKhoanRow) Descriptor() ([]byte, []int) {
	return file_sochitiettaikhoan_proto_rawDescGZIP(), []int{1}
}

func (x *SoChiTietTaiKhoanRow) GetOrderType() int32 {
	if x != nil {
		return x.OrderType
	}
	return 0
}

func (x *SoChiTietTaiKhoanRow) GetOrderNumber() int32 {
	if x != nil {
		return x.OrderNumber
	}
	return 0
}

func (x *SoChiTietTaiKhoanRow) GetBold() bool {
	if x != nil {
		return x.Bold
	}
	return false
}

func (x *SoChiTietTaiKhoanRow) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *SoChiTietTaiKhoanRow) GetAccountCategoryKind() int32 {
	if x != nil {
		return x.AccountCategoryKind
	}
	return 0
}

func (x *SoChiTietTaiKhoanRow) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *SoChiTietTaiKhoanRow) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *SoChiTietTaiKhoanRow) GetTypeId() int32 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

func (x *SoChiTietTaiKhoanRow) GetPostedDate() string {
	if x != nil {
		return x.PostedDate
	}
	return ""
}

func (x *SoChiTietTaiKhoanRow) GetInvoiceDate() string {
	if x != nil {
		return x.InvoiceDate
	}
	return ""
}

func (x *SoChiTietTaiKhoanRow) GetInvoiceNo() string {
	if x != nil {
		return x.InvoiceNo
	}
	return ""
}

func (x *SoChiTietTaiKhoanRow) GetNo() string {
	if x != nil {
		return x.No
	}
	return ""
}

func (x *SoChiTietTaiKhoanRow) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SoChiTietTaiKhoanRow) GetJournalMemo() string {
	if x != nil {
		return x.JournalMemo
	}
	return ""
}

func (x *SoChiTietTaiKhoanRow) GetAccountCorresponding() string {
	if x != nil {
		return x.AccountCorresponding
	}
	return ""
}

func (x *SoChiTietTaiKhoanRow) GetDebitAmount() string {
	if x != nil {
		return x.DebitAmount
	}
	return ""
}

func (x *SoChiTietTaiKhoanRow) GetCreditAmount() string {
	if x != nil {
		return x.CreditAmount
	}
	return ""
}

func (x *SoChiTietTaiKhoanRow) GetDebitAmountOriginal() string {
	if x != nil {
		return x.DebitAmountOriginal
	}
	return ""
}

func (x *SoChiTietTaiKhoanRow) GetCreditAmountOriginal() string {
	if x != nil {
		return x.CreditAmountOriginal
	}
	return ""
}

func (x *SoChiTietTaiKhoanRow) GetClosingDebitAmount() string {
	if x != nil {
		return x.ClosingDebitAmount
	}
	return ""
}

func (x *SoChiTietTaiKhoanRow) GetClosingCreditAmount() string {
	if x != nil {
		return x.ClosingCreditAmount
	}
	return ""
}

func (x *SoChiTietTaiKhoanRow) GetClosingDebitAmountOriginal() string {
	if x != nil {
		return x.ClosingDebitAmountOriginal
	}
	return ""
}

func (x *SoChiTietTaiKhoanRow) GetClosingCreditAmountOriginal() string {
	if x != nil {
		return x.ClosingCreditAmountOriginal
	}
	return ""
}

func (x *SoChiTietTaiKhoanRow) GetExchangeRate() string {
	if x != nil {
		return x.ExchangeRate
	}
	return ""
}

func (x *SoChiTietTaiKhoanRow) GetOrderPriority() int32 {
	if x != nil {
		return x.OrderPriority
	}
	return 0
}

func (x *SoChiTietTaiKhoanRow) GetIsUnreasonableCost() string {
	if x != nil {
		return x.IsUnreasonableCost
	}
	return ""
}

func (x *SoChiTietTaiKhoanRow) GetAccountingObjectCode() string {
	if x != nil {
		return x.AccountingObjectCode
	}
	return ""
}

func (x *SoChiTietTaiKhoanRow) GetAccountingObjectName() string {
	if x != nil {
		return x.AccountingObjectName
	}
	return ""
}

func (x *SoChiTietTaiKhoanRow) GetCustomField() []string {
	if x != nil {
		return x.CustomField
	}
	return nil
}

func (x *SoChiTietTaiKhoanRow) GetCustomFieldDetail() []string {
	if x != nil {
		return x.CustomFieldDetail
	}
	return nil
}

func (x *SoChiTietTaiKhoanRow) GetAccountNameWithAccountNumber() string {
	if x != nil {
		return x.AccountNameWithAccountNumber
	}
	return ""
}

var File_sochitiettaikhoan_proto protoreflect.FileDescriptor

const file_sochitiettaikhoan_proto_rawDesc = "" +
	"\n" +
	"\x17sochitiettaikhoan.proto\x12\x11sochitiettaikhoan\"\xa5\x03\n" +
	"\x18SoChiTietTaiKhoanRequest\x12\x1f\n" +
	"\vcompany_ids\x18\x01 \x03(\tR\n" +
	"companyIds\x12,\n" +
	"\x12primary_company_id\x18\x02 \x01(\tR\x10primaryCompanyId\x12'\n" +
	"\x0faccount_numbers\x18\x03 \x03(\tR\x0eaccountNumbers\x12\x1b\n" +
	"\tfrom_date\x18\x04 \x01(\tR\bfromDate\x12\x17\n" +
	"\ato_date\x18\x05 \x01(\tR\x06toDate\x12\x1f\n" +
	"\vcurrency_id\x18\x06 \x01(\tR\n" +
	"currencyId\x12*\n" +
	"\x11is_financial_book\x18\a \x01(\x05R\x0fisFinancialBook\x12!\n" +
	"\fis_dependent\x18\b \x01(\x05R\visDependent\x12&\n" +
	"\x0fgroup_same_item\x18\t \x01(\x05R\rgroupSameItem\x12$\n" +
	"\x0eis_parent_node\x18\n" +
	" \x01(\bR\fisParentNode\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\v \x01(\tR\tclusterId\"\xa2\n" +
	"\n" +
	"\x14SoChiTietTaiKhoanRow\x12\x1d\n" +
	"\n" +
	"order_type\x18\x01 \x01(\x05R\torderType\x12!\n" +
	"\forder_number\x18\x02 \x01(\x05R\vorderNumber\x12\x12\n" +
	"\x04bold\x18\x03 \x01(\bR\x04bold\x12%\n" +
	"\x0eaccount_number\x18\x04 \x01(\tR\raccountNumber\x122\n" +
	"\x15account_category_kind\x18\x05 \x01(\x05R\x13accountCategoryKind\x12\x15\n" +
	"\x06key_id\x18\x06 \x01(\tR\x05keyId\x12!\n" +
	"\freference_id\x18\a \x01(\tR\vreferenceId\x12\x17\n" +
	"\atype_id\x18\b \x01(\x05R\x06typeId\x12\x1f\n" +
	"\vposted_date\x18\t \x01(\tR\n" +
	"postedDate\x12!\n" +
	"\finvoice_date\x18\n" +
	" \x01(\tR\vinvoiceDate\x12\x1d\n" +
	"\n" +
	"invoice_no\x18\v \x01(\tR\tinvoiceNo\x12\x0e\n" +
	"\x02no\x18\f \x01(\tR\x02no\x12\x16\n" +
	"\x06reason\x18\r \x01(\tR\x06reason\x12!\n" +
	"\fjournal_memo\x18\x0e \x01(\tR\vjournalMemo\x123\n" +
	"\x15account_corresponding\x18\x0f \x01(\tR\x14accountCorresponding\x12!\n" +
	"\fdebit_amount\x18\x10 \x01(\tR\vdebitAmount\x12#\n" +
	"\rcredit_amount\x18\x11 \x01(\tR\fcreditAmount\x122\n" +
	"\x15debit_amount_original\x18\x12 \x01(\tR\x13debitAmountOriginal\x124\n" +
	"\x16credit_amount_original\x18\x13 \x01(\tR\x14creditAmountOriginal\x120\n" +
	"\x14closing_debit_amount\x18\x14 \x01(\tR\x12closingDebitAmount\x122\n" +
	"\x15closing_credit_amount\x18\x15 \x01(\tR\x13closingCreditAmount\x12A\n" +
	"\x1dclosing_debit_amount_original\x18\x16 \x01(\tR\x1aclosingDebitAmountOriginal\x12C\n" +
	"\x1eclosing_credit_amount_original\x18\x17 \x01(\tR\x1bclosingCreditAmountOriginal\x12#\n" +
	"\rexchange_rate\x18\x18 \x01(\tR\fexchangeRate\x12%\n" +
	"\x0eorder_priority\x18\x19 \x01(\x05R\rorderPriority\x120\n" +
	"\x14is_unreasonable_cost\x18\x1a \x01(\tR\x12isUnreasonableCost\x124\n" +
	"\x16accounting_object_code\x18\x1b \x01(\tR\x14accountingObjectCode\x124\n" +
	"\x16accounting_object_name\x18\x1c \x01(\tR\x14accountingObjectName\x12!\n" +
	"\fcustom_field\x18\x1d \x03(\tR\vcustomField\x12.\n" +
	"\x13custom_field_detail\x18\x1e \x03(\tR\x11customFieldDetail\x12F\n" +
	" account_name_with_account_number\x18\x1f \x01(\tR\x1caccountNameWithAccountNumber2\x8a\x01\n" +
	"\x18SoChiTietTaiKhoanService\x12n\n" +
	"\x14GetSoChiTietTaiKhoan\x12+.sochitiettaikhoan.SoChiTietTaiKhoanRequest\x1a'.sochitiettaikhoan.SoChiTietTaiKhoanRow0\x01B\x81\x01\n" +
	"*vn.softdreams.ebweb.grpc.sochitiettaikhoanB\x16SoChiTietTaiKhoanProtoP\x01Z9softdream.vn/go-gateway/internal/so_chi_tiet_tai_khoan/pbb\x06proto3"

var (
	file_sochitiettaikhoan_proto_rawDescOnce sync.Once
	file_sochitiettaikhoan_proto_rawDescData []byte
)

func file_sochitiettaikhoan_proto_rawDescGZIP() []byte {
	file_sochitiettaikhoan_proto_rawDescOnce.Do(func() {
		file_sochitiettaikhoan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sochitiettaikhoan_proto_rawDesc), len(file_sochitiettaikhoan_proto_rawDesc)))
	})
	return file_sochitiettaikhoan_proto_rawDescData
}

var file_sochitiettaikhoan_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sochitiettaikhoan_proto_goTypes = []any{
	(*SoChiTietTaiKhoanRequest)(nil), // 0: sochitiettaikhoan.SoChiTietTaiKhoanRequest
	(*SoChiTietTaiKhoanRow)(nil),     // 1: sochitiettaikhoan.SoChiTietTaiKhoanRow
}
var file_sochitiettaikhoan_proto_depIdxs = []int32{
	0, // 0: sochitiettaikhoan.SoChiTietTaiKhoanService.GetSoChiTietTaiKhoan:input_type -> sochitiettaikhoan.SoChiTietTaiKhoanRequest
	1, // 1: sochitiettaikhoan.SoChiTietTaiKhoanService.GetSoChiTietTaiKhoan:output_type -> sochitiettaikhoan.SoChiTietTaiKhoanRow
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sochitiettaikhoan_proto_init() }
func file_sochitiettaikhoan_proto_init() {
	if File_sochitiettaikhoan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sochitiettaikhoan_proto_rawDesc), len(file_sochitiettaikhoan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sochitiettaikhoan_proto_goTypes,
		DependencyIndexes: file_sochitiettaikhoan_proto_depIdxs,
		MessageInfos:      file_sochitiettaikhoan_proto_msgTypes,
	}.Build()
	File_sochitiettaikhoan_proto = out.File
	file_sochitiettaikhoan_proto_goTypes = nil
	file_sochitiettaikhoan_proto_depIdxs = nil
}
