// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: sochitiettaikhoan.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SoChiTietTaiKhoanService_GetSoChiTietTaiKhoan_FullMethodName = "/sochitiettaikhoan.SoChiTietTaiKhoanService/GetSoChiTietTaiKhoan"
)

// SoChiTietTaiKhoanServiceClient is the client API for SoChiTietTaiKhoanService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SoChiTietTaiKhoanServiceClient interface {
	// Server-streaming: moi dong duoc gui ngay khi scan xong, khong gom ca lo.
	// Giong so_chi_tiet_vat_lieu - day la diem mau chot tranh treo voi bao cao
	// vai tram nghin dong.
	GetSoChiTietTaiKhoan(ctx context.Context, in *SoChiTietTaiKhoanRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SoChiTietTaiKhoanRow], error)
}

type soChiTietTaiKhoanServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSoChiTietTaiKhoanServiceClient(cc grpc.ClientConnInterface) SoChiTietTaiKhoanServiceClient {
	return &soChiTietTaiKhoanServiceClient{cc}
}

func (c *soChiTietTaiKhoanServiceClient) GetSoChiTietTaiKhoan(ctx context.Context, in *SoChiTietTaiKhoanRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SoChiTietTaiKhoanRow], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SoChiTietTaiKhoanService_ServiceDesc.Streams[0], SoChiTietTaiKhoanService_GetSoChiTietTaiKhoan_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SoChiTietTaiKhoanRequest, SoChiTietTaiKhoanRow]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SoChiTietTaiKhoanService_GetSoChiTietTaiKhoanClient = grpc.ServerStreamingClient[SoChiTietTaiKhoanRow]

// SoChiTietTaiKhoanServiceServer is the server API for SoChiTietTaiKhoanService service.
// All implementations must embed UnimplementedSoChiTietTaiKhoanServiceServer
// for forward compatibility.
type SoChiTietTaiKhoanServiceServer interface {
	// Server-streaming: moi dong duoc gui ngay khi scan xong, khong gom ca lo.
	// Giong so_chi_tiet_vat_lieu - day la diem mau chot tranh treo voi bao cao
	// vai tram nghin dong.
	GetSoChiTietTaiKhoan(*SoChiTietTaiKhoanRequest, grpc.ServerStreamingServer[SoChiTietTaiKhoanRow]) error
	mustEmbedUnimplementedSoChiTietTaiKhoanServiceServer()
}

// UnimplementedSoChiTietTaiKhoanServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSoChiTietTaiKhoanServiceServer struct{}

func (UnimplementedSoChiTietTaiKhoanServiceServer) GetSoChiTietTaiKhoan(*SoChiTietTaiKhoanRequest, grpc.ServerStreamingServer[SoChiTietTaiKhoanRow]) error {
	return status.Error(codes.Unimplemented, "method GetSoChiTietTaiKhoan not implemented")
}
func (UnimplementedSoChiTietTaiKhoanServiceServer) mustEmbedUnimplementedSoChiTietTaiKhoanServiceServer() {
}
func (UnimplementedSoChiTietTaiKhoanServiceServer) testEmbeddedByValue() {}

// UnsafeSoChiTietTaiKhoanServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SoChiTietTaiKhoanServiceServer will
// result in compilation errors.
type UnsafeSoChiTietTaiKhoanServiceServer interface {
	mustEmbedUnimplementedSoChiTietTaiKhoanServiceServer()
}

func RegisterSoChiTietTaiKhoanServiceServer(s grpc.ServiceRegistrar, srv SoChiTietTaiKhoanServiceServer) {
	// If the following call panics, it indicates UnimplementedSoChiTietTaiKhoanServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SoChiTietTaiKhoanService_ServiceDesc, srv)
}

func _SoChiTietTaiKhoanService_GetSoChiTietTaiKhoan_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SoChiTietTaiKhoanRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SoChiTietTaiKhoanServiceServer).GetSoChiTietTaiKhoan(m, &grpc.GenericServerStream[SoChiTietTaiKhoanRequest, SoChiTietTaiKhoanRow]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SoChiTietTaiKhoanService_GetSoChiTietTaiKhoanServer = grpc.ServerStreamingServer[SoChiTietTaiKhoanRow]

// SoChiTietTaiKhoanService_ServiceDesc is the grpc.ServiceDesc for SoChiTietTaiKhoanService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SoChiTietTaiKhoanService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sochitiettaikhoan.SoChiTietTaiKhoanService",
	HandlerType: (*SoChiTietTaiKhoanServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetSoChiTietTaiKhoan",
			Handler:       _SoChiTietTaiKhoanService_GetSoChiTietTaiKhoan_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sochitiettaikhoan.proto",
}
