// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: soketoanchitietquytienmat.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SoKeToanChiTietQuyTienMatService_GetSoKeToanChiTietQuyTienMat_FullMethodName = "/soketoanchitietquytienmat.SoKeToanChiTietQuyTienMatService/GetSoKeToanChiTietQuyTienMat"
)

// SoKeToanChiTietQuyTienMatServiceClient is the client API for SoKeToanChiTietQuyTienMatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SoKeToanChiTietQuyTienMatServiceClient interface {
	// Server-streaming: moi dong duoc gui ngay khi dung xong, khong gom ca lo.
	//
	// Bao cao nay co cot SoTon LUY KE nen thu tu dong la mot phan cua tinh dung
	// dan, khong phai chuyen trinh bay. Client PHAI giu nguyen thu tu nhan duoc.
	GetSoKeToanChiTietQuyTienMat(ctx context.Context, in *SoKeToanChiTietQuyTienMatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SoKeToanChiTietQuyTienMatRow], error)
}

type soKeToanChiTietQuyTienMatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSoKeToanChiTietQuyTienMatServiceClient(cc grpc.ClientConnInterface) SoKeToanChiTietQuyTienMatServiceClient {
	return &soKeToanChiTietQuyTienMatServiceClient{cc}
}

func (c *soKeToanChiTietQuyTienMatServiceClient) GetSoKeToanChiTietQuyTienMat(ctx context.Context, in *SoKeToanChiTietQuyTienMatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SoKeToanChiTietQuyTienMatRow], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SoKeToanChiTietQuyTienMatService_ServiceDesc.Streams[0], SoKeToanChiTietQuyTienMatService_GetSoKeToanChiTietQuyTienMat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SoKeToanChiTietQuyTienMatRequest, SoKeToanChiTietQuyTienMatRow]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SoKeToanChiTietQuyTienMatService_GetSoKeToanChiTietQuyTienMatClient = grpc.ServerStreamingClient[SoKeToanChiTietQuyTienMatRow]

// SoKeToanChiTietQuyTienMatServiceServer is the server API for SoKeToanChiTietQuyTienMatService service.
// All implementations must embed UnimplementedSoKeToanChiTietQuyTienMatServiceServer
// for forward compatibility.
type SoKeToanChiTietQuyTienMatServiceServer interface {
	// Server-streaming: moi dong duoc gui ngay khi dung xong, khong gom ca lo.
	//
	// Bao cao nay co cot SoTon LUY KE nen thu tu dong la mot phan cua tinh dung
	// dan, khong phai chuyen trinh bay. Client PHAI giu nguyen thu tu nhan duoc.
	GetSoKeToanChiTietQuyTienMat(*SoKeToanChiTietQuyTienMatRequest, grpc.ServerStreamingServer[SoKeToanChiTietQuyTienMatRow]) error
	mustEmbedUnimplementedSoKeToanChiTietQuyTienMatServiceServer()
}

// UnimplementedSoKeToanChiTietQuyTienMatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSoKeToanChiTietQuyTienMatServiceServer struct{}

func (UnimplementedSoKeToanChiTietQuyTienMatServiceServer) GetSoKeToanChiTietQuyTienMat(*SoKeToanChiTietQuyTienMatRequest, grpc.ServerStreamingServer[SoKeToanChiTietQuyTienMatRow]) error {
	return status.Error(codes.Unimplemented, "method GetSoKeToanChiTietQuyTienMat not implemented")
}
func (UnimplementedSoKeToanChiTietQuyTienMatServiceServer) mustEmbedUnimplementedSoKeToanChiTietQuyTienMatServiceServer() {
}
func (UnimplementedSoKeToanChiTietQuyTienMatServiceServer) testEmbeddedByValue() {}

// UnsafeSoKeToanChiTietQuyTienMatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SoKeToanChiTietQuyTienMatServiceServer will
// result in compilation errors.
type UnsafeSoKeToanChiTietQuyTienMatServiceServer interface {
	mustEmbedUnimplementedSoKeToanChiTietQuyTienMatServiceServer()
}

func RegisterSoKeToanChiTietQuyTienMatServiceServer(s grpc.ServiceRegistrar, srv SoKeToanChiTietQuyTienMatServiceServer) {
	// If the following call panics, it indicates UnimplementedSoKeToanChiTietQuyTienMatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SoKeToanChiTietQuyTienMatService_ServiceDesc, srv)
}

func _SoKeToanChiTietQuyTienMatService_GetSoKeToanChiTietQuyTienMat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SoKeToanChiTietQuyTienMatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SoKeToanChiTietQuyTienMatServiceServer).GetSoKeToanChiTietQuyTienMat(m, &grpc.GenericServerStream[SoKeToanChiTietQuyTienMatRequest, SoKeToanChiTietQuyTienMatRow]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SoKeToanChiTietQuyTienMatService_GetSoKeToanChiTietQuyTienMatServer = grpc.ServerStreamingServer[SoKeToanChiTietQuyTienMatRow]

// SoKeToanChiTietQuyTienMatService_ServiceDesc is the grpc.ServiceDesc for SoKeToanChiTietQuyTienMatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SoKeToanChiTietQuyTienMatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "soketoanchitietquytienmat.SoKeToanChiTietQuyTienMatService",
	HandlerType: (*SoKeToanChiTietQuyTienMatServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetSoKeToanChiTietQuyTienMat",
			Handler:       _SoKeToanChiTietQuyTienMatService_GetSoKeToanChiTietQuyTienMat_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "soketoanchitietquytienmat.proto",
}
