// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: soketoanchitietquytienmat.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SoKeToanChiTietQuyTienMatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID DA SWAP theo quy uoc SQL Server <-> ClickHouse.
	// Viec swap do Java lam (SqlServerUuidSwap); Go chi nhan UUID chuan.
	CompanyIds       []string `protobuf:"bytes,1,rep,name=company_ids,json=companyIds,proto3" json:"company_ids,omitempty"`
	PrimaryCompanyId string   `protobuf:"bytes,2,opt,name=primary_company_id,json=primaryCompanyId,proto3" json:"primary_company_id,omitempty"`
	// Cac tai khoan quy tien mat nguoi dung chon (vd 1111, 1112...).
	//
	// Java PHAI gop cac nguon trong RequestReport truoc khi gui — Go nhan danh
	// sach da chuan hoa.
	//
	// LUU Y: so hieu tai khoan CO THE chua khoang trang va gach ngang.
	// "154 - TT" la mot tai khoan THAT, ton tai song song voi "154".
	AccountNumbers []string `protobuf:"bytes,3,rep,name=account_numbers,json=accountNumbers,proto3" json:"account_numbers,omitempty"`
	FromDate       string   `protobuf:"bytes,4,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"` // YYYY-MM-DD
	ToDate         string   `protobuf:"bytes,5,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`       // YYYY-MM-DD
	// "TH" = tat ca loai tien; nguoc lai loc theo ma.
	CurrencyId string `protobuf:"bytes,6,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`
	// 1 = so tai chinh -> proc @TypeLedger = 0, cot NoFBook
	// 0 = so quan tri  -> proc @TypeLedger = 1, cot NoMBook
	//
	// CHU Y CHIEU DAO: proc nhan thang @TypeLedger nen 0 moi la so tai chinh.
	// Go phai doi: typeLedger = (is_financial_book == 1) ? 0 : 1
	// Chon nham chieu la toan bo bao cao lay sai so ma khong co loi nao bao ra.
	IsFinancialBook int32 `protobuf:"varint,7,opt,name=is_financial_book,json=isFinancialBook,proto3" json:"is_financial_book,omitempty"`
	// 1 = gop ca don vi phu thuoc (bridge_org_scope)
	IsDependent int32 `protobuf:"varint,8,opt,name=is_dependent,json=isDependent,proto3" json:"is_dependent,omitempty"`
	// 1 = cong gop but toan cung chung tu.
	//
	// KHAC voi So chi tiet cac tai khoan: proc nay chi GROUP BY BON cot
	//
	//	GL.ReferenceID, Account, AccountCorresponding, AccountingObjectID
	//
	// va bo han moi cot chieu. Dung ap quy uoc 19 cot cua bao cao kia sang day.
	GroupSameItem int32 `protobuf:"varint,9,opt,name=group_same_item,json=groupSameItem,proto3" json:"group_same_item,omitempty"`
	// 0 = hien thi so QUY DOI      (debit_amount)
	// 1 = hien thi so NGUYEN TE    (debit_amount_original)
	//
	// Chi anh huong cot phat_sinh_no / phat_sinh_co / so_ton.
	// Cac cot *_qd LUON la ban quy doi.
	TypeShowCurrency int32 `protobuf:"varint,10,opt,name=type_show_currency,json=typeShowCurrency,proto3" json:"type_show_currency,omitempty"`
	// Multi-cluster. Rong = khong loc.
	ClusterId     string `protobuf:"bytes,11,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SoKeToanChiTietQuyTienMatRequest) Reset() {
	*x = SoKeToanChiTietQuyTienMatRequest{}
	mi := &file_soketoanchitietquytienmat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SoKeToanChiTietQuyTienMatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoKeToanChiTietQuyTienMatRequest) ProtoMessage() {}

func (x *SoKeToanChiTietQuyTienMatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_soketoanchitietquytienmat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoKeToanChiTietQuyTienMatRequest.ProtoReflect.Descriptor instead.
func (*SoKeToanChiTietQuyTienMatRequest) Descriptor() ([]byte, []int) {
	return file_soketoanchitietquytienmat_proto_rawDescGZIP(), []int{0}
}

func (x *SoKeToanChiTietQuyTienMatRequest) GetCompanyIds() []string {
	if x != nil {
		return x.CompanyIds
	}
	return nil
}

func (x *SoKeToanChiTietQuyTienMatRequest) GetPrimaryCompanyId() string {
	if x != nil {
		return x.PrimaryCompanyId
	}
	return ""
}

func (x *SoKeToanChiTietQuyTienMatRequest) GetAccountNumbers() []string {
	if x != nil {
		return x.AccountNumbers
	}
	return nil
}

func (x *SoKeToanChiTietQuyTienMatRequest) GetFromDate() string {
	if x != nil {
		return x.FromDate
	}
	return ""
}

func (x *SoKeToanChiTietQuyTienMatRequest) GetToDate() string {
	if x != nil {
		return x.ToDate
	}
	return ""
}

func (x *SoKeToanChiTietQuyTienMatRequest) GetCurrencyId() string {
	if x != nil {
		return x.CurrencyId
	}
	return ""
}

func (x *SoKeToanChiTietQuyTienMatRequest) GetIsFinancialBook() int32 {
	if x != nil {
		return x.IsFinancialBook
	}
	return 0
}

func (x *SoKeToanChiTietQuyTienMatRequest) GetIsDependent() int32 {
	if x != nil {
		return x.IsDependent
	}
	return 0
}

func (x *SoKeToanChiTietQuyTienMatRequest) GetGroupSameItem() int32 {
	if x != nil {
		return x.GroupSameItem
	}
	return 0
}

func (x *SoKeToanChiTietQuyTienMatRequest) GetTypeShowCurrency() int32 {
	if x != nil {
		return x.TypeShowCurrency
	}
	return 0
}

func (x *SoKeToanChiTietQuyTienMatRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

// Mot dong cua so ke toan chi tiet quy tien mat.
// Anh xa 1-1 voi bang #Result cua Proc_SO_KE_TOAN_CHI_TIET_QUY_TIEN_MAT.
type SoKeToanChiTietQuyTienMatRow struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CHI CO BA GIA TRI:
	//
	//	0 = Ton dau ky
	//	1 = Phat sinh trong ky
	//	2 = Cong nhom (dong cuoi moi tai khoan)
	//
	// KHONG co "So du cuoi ky" nhu So chi tiet cac tai khoan. Proc khong sinh
	// dong do. So du cuoi ky chinh la cot so_ton cua dong position_order = 2.
	PositionOrder int32 `protobuf:"varint,1,opt,name=position_order,json=positionOrder,proto3" json:"position_order,omitempty"`
	// 0 = Phieu thu, 1 = Phieu chi.
	//
	// Mot but toan vua co No vua co Co sinh HAI dong: mot thu, mot chi. Chung
	// cung reference_id nhung khac ca_type.
	CaType      int32  `protobuf:"varint,2,opt,name=ca_type,json=caType,proto3" json:"ca_type,omitempty"`
	ReferenceId string `protobuf:"bytes,3,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"` // UUID, rong neu la dong tong
	TypeId      int32  `protobuf:"varint,4,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	Date        string `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`                               // ngay chung tu (GL.Date), YYYY-MM-DD
	PostedDate  string `protobuf:"bytes,6,opt,name=posted_date,json=postedDate,proto3" json:"posted_date,omitempty"` // ngay hach toan (GL.PostedDate)
	// Cung mot so hieu chung tu, dat vao cot nao tuy ca_type.
	ReceiptRefNo         string `protobuf:"bytes,7,opt,name=receipt_ref_no,json=receiptRefNo,proto3" json:"receipt_ref_no,omitempty"` // so phieu thu, chi co khi ca_type = 0
	PaymentRefNo         string `protobuf:"bytes,8,opt,name=payment_ref_no,json=paymentRefNo,proto3" json:"payment_ref_no,omitempty"` // so phieu chi, chi co khi ca_type = 1
	JournalMemo          string `protobuf:"bytes,9,opt,name=journal_memo,json=journalMemo,proto3" json:"journal_memo,omitempty"`
	Reason               string `protobuf:"bytes,10,opt,name=reason,proto3" json:"reason,omitempty"`
	Note                 string `protobuf:"bytes,11,opt,name=note,proto3" json:"note,omitempty"`
	Account              string `protobuf:"bytes,12,opt,name=account,proto3" json:"account,omitempty"`                                                       // TK quy tien mat
	AccountCorresponding string `protobuf:"bytes,13,opt,name=account_corresponding,json=accountCorresponding,proto3" json:"account_corresponding,omitempty"` // TK doi ung
	OrderPriority        int32  `protobuf:"varint,14,opt,name=order_priority,json=orderPriority,proto3" json:"order_priority,omitempty"`
	// ── TIEN TE ──────────────────────────────────────────────────────────────
	// Dung STRING, KHONG dung double.
	//
	// Nguon la Decimal(25,10) — 25 chu so vuot xa do chinh xac cua double
	// (~15-17 chu so). Voi so ke toan thi lech mot dong cung la loi.
	// Java parse lai bang new BigDecimal(s).
	//
	// Cot khong hau to: theo type_show_currency (quy doi hoac nguyen te)
	// Cot _qd: LUON la ban quy doi
	PhatSinhNo   string `protobuf:"bytes,15,opt,name=phat_sinh_no,json=phatSinhNo,proto3" json:"phat_sinh_no,omitempty"`
	PhatSinhCo   string `protobuf:"bytes,16,opt,name=phat_sinh_co,json=phatSinhCo,proto3" json:"phat_sinh_co,omitempty"`
	SoTon        string `protobuf:"bytes,17,opt,name=so_ton,json=soTon,proto3" json:"so_ton,omitempty"` // ton quy LUY KE
	PhatSinhNoQd string `protobuf:"bytes,18,opt,name=phat_sinh_no_qd,json=phatSinhNoQd,proto3" json:"phat_sinh_no_qd,omitempty"`
	PhatSinhCoQd string `protobuf:"bytes,19,opt,name=phat_sinh_co_qd,json=phatSinhCoQd,proto3" json:"phat_sinh_co_qd,omitempty"`
	SoTonQd      string `protobuf:"bytes,20,opt,name=so_ton_qd,json=soTonQd,proto3" json:"so_ton_qd,omitempty"`
	ExchangeRate string `protobuf:"bytes,21,opt,name=exchange_rate,json=exchangeRate,proto3" json:"exchange_rate,omitempty"`
	// ── CHIEU ────────────────────────────────────────────────────────────────
	AccountingObjectCode string `protobuf:"bytes,22,opt,name=accounting_object_code,json=accountingObjectCode,proto3" json:"accounting_object_code,omitempty"`
	AccountingObjectName string `protobuf:"bytes,23,opt,name=accounting_object_name,json=accountingObjectName,proto3" json:"accounting_object_name,omitempty"`
	// SAU NHOM DUOI DAY HIEN TRA VE CHUOI RONG.
	//
	// fact_gl_entry_line chua co cac cot khoa ngoai tuong ung
	// (ExpenseItemID, BudgetItemID, DepartmentID, CostSetID, ContractID,
	// StatisticsCodeID). Chung nam o dbo.GeneralLedger nhung chua chay qua
	// Debezium/Flink.
	//
	// KHONG anh huong so lieu: nhanh gop cua proc bo han chung
	//
	//	group by GL.ReferenceID, Account, AccountCorresponding, AccountingObjectID
	//
	// nen chung chi de hien thi o che do chi tiet.
	//
	// Giu field o day de hop dong API on dinh — khi fact duoc bo sung thi chi
	// can dien, khong phai doi proto hay sua frontend.
	ExpenseItemCode      string `protobuf:"bytes,24,opt,name=expense_item_code,json=expenseItemCode,proto3" json:"expense_item_code,omitempty"`
	ExpenseItemName      string `protobuf:"bytes,25,opt,name=expense_item_name,json=expenseItemName,proto3" json:"expense_item_name,omitempty"`
	BudgetItemCode       string `protobuf:"bytes,26,opt,name=budget_item_code,json=budgetItemCode,proto3" json:"budget_item_code,omitempty"`
	BudgetItemName       string `protobuf:"bytes,27,opt,name=budget_item_name,json=budgetItemName,proto3" json:"budget_item_name,omitempty"`
	OrganizationUnitCode string `protobuf:"bytes,28,opt,name=organization_unit_code,json=organizationUnitCode,proto3" json:"organization_unit_code,omitempty"` // tu GL.DepartmentID
	OrganizationUnitName string `protobuf:"bytes,29,opt,name=organization_unit_name,json=organizationUnitName,proto3" json:"organization_unit_name,omitempty"`
	CostSetCode          string `protobuf:"bytes,30,opt,name=cost_set_code,json=costSetCode,proto3" json:"cost_set_code,omitempty"`
	CostSetName          string `protobuf:"bytes,31,opt,name=cost_set_name,json=costSetName,proto3" json:"cost_set_name,omitempty"`
	ContractNo           string `protobuf:"bytes,32,opt,name=contract_no,json=contractNo,proto3" json:"contract_no,omitempty"`
	StatisticsCodeCode   string `protobuf:"bytes,33,opt,name=statistics_code_code,json=statisticsCodeCode,proto3" json:"statistics_code_code,omitempty"`
	StatisticsCodeName   string `protobuf:"bytes,34,opt,name=statistics_code_name,json=statisticsCodeName,proto3" json:"statistics_code_name,omitempty"`
	// Luon dung 5 phan tu, index 0..4.
	CustomField       []string `protobuf:"bytes,35,rep,name=custom_field,json=customField,proto3" json:"custom_field,omitempty"`
	CustomFieldDetail []string `protobuf:"bytes,36,rep,name=custom_field_detail,json=customFieldDetail,proto3" json:"custom_field_detail,omitempty"`
	// true khi position_order != 1. Frontend dung de bold va an so tien theo cot.
	IsSumCol      bool `protobuf:"varint,37,opt,name=is_sum_col,json=isSumCol,proto3" json:"is_sum_col,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SoKeToanChiTietQuyTienMatRow) Reset() {
	*x = SoKeToanChiTietQuyTienMatRow{}
	mi := &file_soketoanchitietquytienmat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SoKeToanChiTietQuyTienMatRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoKeToanChiTietQuyTienMatRow) ProtoMessage() {}

func (x *SoKeToanChiTietQuyTienMatRow) ProtoReflect() protoreflect.Message {
	mi := &file_soketoanchitietquytienmat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoKeToanChiTietQuyTienMatRow.ProtoReflect.Descriptor instead.
func (*SoKeToanChiTietQuyTienMatRow) Descriptor() ([]byte, []int) {
	return file_soketoanchitietquytienmat_proto_rawDescGZIP(), []int{1}
}

func (x *SoKeToanChiTietQuyTienMatRow) GetPositionOrder() int32 {
	if x != nil {
		return x.PositionOrder
	}
	return 0
}

func (x *SoKeToanChiTietQuyTienMatRow) GetCaType() int32 {
	if x != nil {
		return x.CaType
	}
	return 0
}

func (x *SoKeToanChiTietQuyTienMatRow) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *SoKeToanChiTietQuyTienMatRow) GetTypeId() int32 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

func (x *SoKeToanChiTietQuyTienMatRow) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *SoKeToanChiTietQuyTienMatRow) GetPostedDate() string {
	if x != nil {
		return x.PostedDate
	}
	return ""
}

func (x *SoKeToanChiTietQuyTienMatRow) GetReceiptRefNo() string {
	if x != nil {
		return x.ReceiptRefNo
	}
	return ""
}

func (x *SoKeToanChiTietQuyTienMatRow) GetPaymentRefNo() string {
	if x != nil {
		return x.PaymentRefNo
	}
	return ""
}

func (x *SoKeToanChiTietQuyTienMatRow) GetJournalMemo() string {
	if x != nil {
		return x.JournalMemo
	}
	return ""
}

func (x *SoKeToanChiTietQuyTienMatRow) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SoKeToanChiTietQuyTienMatRow) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *SoKeToanChiTietQuyTienMatRow) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *SoKeToanChiTietQuyTienMatRow) GetAccountCorresponding() string {
	if x != nil {
		return x.AccountCorresponding
	}
	return ""
}

func (x *SoKeToanChiTietQuyTienMatRow) GetOrderPriority() int32 {
	if x != nil {
		return x.OrderPriority
	}
	return 0
}

func (x *SoKeToanChiTietQuyTienMatRow) GetPhatSinhNo() string {
	if x != nil {
		return x.PhatSinhNo
	}
	return ""
}

func (x *SoKeToanChiTietQuyTienMatRow) GetPhatSinhCo() string {
	if x != nil {
		return x.PhatSinhCo
	}
	return ""
}

func (x *SoKeToanChiTietQuyTienMatRow) GetSoTon() string {
	if x != nil {
		return x.SoTon
	}
	return ""
}

func (x *SoKeToanChiTietQuyTienMatRow) GetPhatSinhNoQd() string {
	if x != nil {
		return x.PhatSinhNoQd
	}
	return ""
}

func (x *SoKeToanChiTietQuyTienMatRow) GetPhatSinhCoQd() string {
	if x != nil {
		return x.PhatSinhCoQd
	}
	return ""
}

func (x *SoKeToanChiTietQuyTienMatRow) GetSoTonQd() string {
	if x != nil {
		return x.SoTonQd
	}
	return ""
}

func (x *SoKeToanChiTietQuyTienMatRow) GetExchangeRate() string {
	if x != nil {
		return x.ExchangeRate
	}
	return ""
}

func (x *SoKeToanChiTietQuyTienMatRow) GetAccountingObjectCode() string {
	if x != nil {
		return x.AccountingObjectCode
	}
	return ""
}

func (x *SoKeToanChiTietQuyTienMatRow) GetAccountingObjectName() string {
	if x != nil {
		return x.AccountingObjectName
	}
	return ""
}

func (x *SoKeToanChiTietQuyTienMatRow) GetExpenseItemCode() string {
	if x != nil {
		return x.ExpenseItemCode
	}
	return ""
}

func (x *SoKeToanChiTietQuyTienMatRow) GetExpenseItemName() string {
	if x != nil {
		return x.ExpenseItemName
	}
	return ""
}

func (x *SoKeToanChiTietQuyTienMatRow) GetBudgetItemCode() string {
	if x != nil {
		return x.BudgetItemCode
	}
	return ""
}

func (x *SoKeToanChiTietQuyTienMatRow) GetBudgetItemName() string {
	if x != nil {
		return x.BudgetItemName
	}
	return ""
}

func (x *SoKeToanChiTietQuyTienMatRow) GetOrganizationUnitCode() string {
	if x != nil {
		return x.OrganizationUnitCode
	}
	return ""
}

func (x *SoKeToanChiTietQuyTienMatRow) GetOrganizationUnitName() string {
	if x != nil {
		return x.OrganizationUnitName
	}
	return ""
}

func (x *SoKeToanChiTietQuyTienMatRow) GetCostSetCode() string {
	if x != nil {
		return x.CostSetCode
	}
	return ""
}

func (x *SoKeToanChiTietQuyTienMatRow) GetCostSetName() string {
	if x != nil {
		return x.CostSetName
	}
	return ""
}

func (x *SoKeToanChiTietQuyTienMatRow) GetContractNo() string {
	if x != nil {
		return x.ContractNo
	}
	return ""
}

func (x *SoKeToanChiTietQuyTienMatRow) GetStatisticsCodeCode() string {
	if x != nil {
		return x.StatisticsCodeCode
	}
	return ""
}

func (x *SoKeToanChiTietQuyTienMatRow) GetStatisticsCodeName() string {
	if x != nil {
		return x.StatisticsCodeName
	}
	return ""
}

func (x *SoKeToanChiTietQuyTienMatRow) GetCustomField() []string {
	if x != nil {
		return x.CustomField
	}
	return nil
}

func (x *SoKeToanChiTietQuyTienMatRow) GetCustomFieldDetail() []string {
	if x != nil {
		return x.CustomFieldDetail
	}
	return nil
}

func (x *SoKeToanChiTietQuyTienMatRow) GetIsSumCol() bool {
	if x != nil {
		return x.IsSumCol
	}
	return false
}

var File_soketoanchitietquytienmat_proto protoreflect.FileDescriptor

const file_soketoanchitietquytienmat_proto_rawDesc = "" +
	"\n" +
	"\x1fsoketoanchitietquytienmat.proto\x12\x19soketoanchitietquytienmat\"\xb5\x03\n" +
	" SoKeToanChiTietQuyTienMatRequest\x12\x1f\n" +
	"\vcompany_ids\x18\x01 \x03(\tR\n" +
	"companyIds\x12,\n" +
	"\x12primary_company_id\x18\x02 \x01(\tR\x10primaryCompanyId\x12'\n" +
	"\x0faccount_numbers\x18\x03 \x03(\tR\x0eaccountNumbers\x12\x1b\n" +
	"\tfrom_date\x18\x04 \x01(\tR\bfromDate\x12\x17\n" +
	"\ato_date\x18\x05 \x01(\tR\x06toDate\x12\x1f\n" +
	"\vcurrency_id\x18\x06 \x01(\tR\n" +
	"currencyId\x12*\n" +
	"\x11is_financial_book\x18\a \x01(\x05R\x0fisFinancialBook\x12!\n" +
	"\fis_dependent\x18\b \x01(\x05R\visDependent\x12&\n" +
	"\x0fgroup_same_item\x18\t \x01(\x05R\rgroupSameItem\x12,\n" +
	"\x12type_show_currency\x18\n" +
	" \x01(\x05R\x10typeShowCurrency\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\v \x01(\tR\tclusterId\"\x8c\v\n" +
	"\x1cSoKeToanChiTietQuyTienMatRow\x12%\n" +
	"\x0eposition_order\x18\x01 \x01(\x05R\rpositionOrder\x12\x17\n" +
	"\aca_type\x18\x02 \x01(\x05R\x06caType\x12!\n" +
	"\freference_id\x18\x03 \x01(\tR\vreferenceId\x12\x17\n" +
	"\atype_id\x18\x04 \x01(\x05R\x06typeId\x12\x12\n" +
	"\x04date\x18\x05 \x01(\tR\x04date\x12\x1f\n" +
	"\vposted_date\x18\x06 \x01(\tR\n" +
	"postedDate\x12$\n" +
	"\x0ereceipt_ref_no\x18\a \x01(\tR\freceiptRefNo\x12$\n" +
	"\x0epayment_ref_no\x18\b \x01(\tR\fpaymentRefNo\x12!\n" +
	"\fjournal_memo\x18\t \x01(\tR\vjournalMemo\x12\x16\n" +
	"\x06reason\x18\n" +
	" \x01(\tR\x06reason\x12\x12\n" +
	"\x04note\x18\v \x01(\tR\x04note\x12\x18\n" +
	"\aaccount\x18\f \x01(\tR\aaccount\x123\n" +
	"\x15account_corresponding\x18\r \x01(\tR\x14accountCorresponding\x12%\n" +
	"\x0eorder_priority\x18\x0e \x01(\x05R\rorderPriority\x12 \n" +
	"\fphat_sinh_no\x18\x0f \x01(\tR\n" +
	"phatSinhNo\x12 \n" +
	"\fphat_sinh_co\x18\x10 \x01(\tR\n" +
	"phatSinhCo\x12\x15\n" +
	"\x06so_ton\x18\x11 \x01(\tR\x05soTon\x12%\n" +
	"\x0fphat_sinh_no_qd\x18\x12 \x01(\tR\fphatSinhNoQd\x12%\n" +
	"\x0fphat_sinh_co_qd\x18\x13 \x01(\tR\fphatSinhCoQd\x12\x1a\n" +
	"\tso_ton_qd\x18\x14 \x01(\tR\asoTonQd\x12#\n" +
	"\rexchange_rate\x18\x15 \x01(\tR\fexchangeRate\x124\n" +
	"\x16accounting_object_code\x18\x16 \x01(\tR\x14accountingObjectCode\x124\n" +
	"\x16accounting_object_name\x18\x17 \x01(\tR\x14accountingObjectName\x12*\n" +
	"\x11expense_item_code\x18\x18 \x01(\tR\x0fexpenseItemCode\x12*\n" +
	"\x11expense_item_name\x18\x19 \x01(\tR\x0fexpenseItemName\x12(\n" +
	"\x10budget_item_code\x18\x1a \x01(\tR\x0ebudgetItemCode\x12(\n" +
	"\x10budget_item_name\x18\x1b \x01(\tR\x0ebudgetItemName\x124\n" +
	"\x16organization_unit_code\x18\x1c \x01(\tR\x14organizationUnitCode\x124\n" +
	"\x16organization_unit_name\x18\x1d \x01(\tR\x14organizationUnitName\x12\"\n" +
	"\rcost_set_code\x18\x1e \x01(\tR\vcostSetCode\x12\"\n" +
	"\rcost_set_name\x18\x1f \x01(\tR\vcostSetName\x12\x1f\n" +
	"\vcontract_no\x18  \x01(\tR\n" +
	"contractNo\x120\n" +
	"\x14statistics_code_code\x18! \x01(\tR\x12statisticsCodeCode\x120\n" +
	"\x14statistics_code_name\x18\" \x01(\tR\x12statisticsCodeName\x12!\n" +
	"\fcustom_field\x18# \x03(\tR\vcustomField\x12.\n" +
	"\x13custom_field_detail\x18$ \x03(\tR\x11customFieldDetail\x12\x1c\n" +
	"\n" +
	"is_sum_col\x18% \x01(\bR\bisSumCol2\xbb\x01\n" +
	" SoKeToanChiTietQuyTienMatService\x12\x96\x01\n" +
	"\x1cGetSoKeToanChiTietQuyTienMat\x12;.soketoanchitietquytienmat.SoKeToanChiTietQuyTienMatRequest\x1a7.soketoanchitietquytienmat.SoKeToanChiTietQuyTienMatRow0\x01B\x9c\x01\n" +
	"2vn.softdreams.ebweb.grpc.soketoanchitietquytienmatB\x1eSoKeToanChiTietQuyTienMatProtoP\x01ZDsoftdream.vn/go-gateway/internal/so_ke_toan_chi_tiet_quy_tien_mat/pbb\x06proto3"

var (
	file_soketoanchitietquytienmat_proto_rawDescOnce sync.Once
	file_soketoanchitietquytienmat_proto_rawDescData []byte
)

func file_soketoanchitietquytienmat_proto_rawDescGZIP() []byte {
	file_soketoanchitietquytienmat_proto_rawDescOnce.Do(func() {
		file_soketoanchitietquytienmat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_soketoanchitietquytienmat_proto_rawDesc), len(file_soketoanchitietquytienmat_proto_rawDesc)))
	})
	return file_soketoanchitietquytienmat_proto_rawDescData
}

var file_soketoanchitietquytienmat_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_soketoanchitietquytienmat_proto_goTypes = []any{
	(*SoKeToanChiTietQuyTienMatRequest)(nil), // 0: soketoanchitietquytienmat.SoKeToanChiTietQuyTienMatRequest
	(*SoKeToanChiTietQuyTienMatRow)(nil),     // 1: soketoanchitietquytienmat.SoKeToanChiTietQuyTienMatRow
}
var file_soketoanchitietquytienmat_proto_depIdxs = []int32{
	0, // 0: soketoanchitietquytienmat.SoKeToanChiTietQuyTienMatService.GetSoKeToanChiTietQuyTienMat:input_type -> soketoanchitietquytienmat.SoKeToanChiTietQuyTienMatRequest
	1, // 1: soketoanchitietquytienmat.SoKeToanChiTietQuyTienMatService.GetSoKeToanChiTietQuyTienMat:output_type -> soketoanchitietquytienmat.SoKeToanChiTietQuyTienMatRow
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_soketoanchitietquytienmat_proto_init() }
func file_soketoanchitietquytienmat_proto_init() {
	if File_soketoanchitietquytienmat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_soketoanchitietquytienmat_proto_rawDesc), len(file_soketoanchitietquytienmat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_soketoanchitietquytienmat_proto_goTypes,
		DependencyIndexes: file_soketoanchitietquytienmat_proto_depIdxs,
		MessageInfos:      file_soketoanchitietquytienmat_proto_msgTypes,
	}.Build()
	File_soketoanchitietquytienmat_proto = out.File
	file_soketoanchitietquytienmat_proto_goTypes = nil
	file_soketoanchitietquytienmat_proto_depIdxs = nil
}
