// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: sochitietvatlieu.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SoChiTietVatLieuService_GetSoChiTietVatLieu_FullMethodName = "/sochitietvatlieu.SoChiTietVatLieuService/GetSoChiTietVatLieu"
)

// SoChiTietVatLieuServiceClient is the client API for SoChiTietVatLieuService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ============================================================================
// Server Streaming RPC - Go gui TUNG DONG ngay khi doc duoc tu ClickHouse
// (khong buffer het 500k dong vao RAM roi moi gui 1 cuc nhu HTTP/JSON truoc
// day - day chinh la ly do gay treo voi bao cao lon).
// ============================================================================
type SoChiTietVatLieuServiceClient interface {
	GetSoChiTietVatLieu(ctx context.Context, in *SoChiTietVatLieuRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SoChiTietVatLieuRow], error)
}

type soChiTietVatLieuServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSoChiTietVatLieuServiceClient(cc grpc.ClientConnInterface) SoChiTietVatLieuServiceClient {
	return &soChiTietVatLieuServiceClient{cc}
}

func (c *soChiTietVatLieuServiceClient) GetSoChiTietVatLieu(ctx context.Context, in *SoChiTietVatLieuRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SoChiTietVatLieuRow], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SoChiTietVatLieuService_ServiceDesc.Streams[0], SoChiTietVatLieuService_GetSoChiTietVatLieu_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SoChiTietVatLieuRequest, SoChiTietVatLieuRow]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SoChiTietVatLieuService_GetSoChiTietVatLieuClient = grpc.ServerStreamingClient[SoChiTietVatLieuRow]

// SoChiTietVatLieuServiceServer is the server API for SoChiTietVatLieuService service.
// All implementations must embed UnimplementedSoChiTietVatLieuServiceServer
// for forward compatibility.
//
// ============================================================================
// Server Streaming RPC - Go gui TUNG DONG ngay khi doc duoc tu ClickHouse
// (khong buffer het 500k dong vao RAM roi moi gui 1 cuc nhu HTTP/JSON truoc
// day - day chinh la ly do gay treo voi bao cao lon).
// ============================================================================
type SoChiTietVatLieuServiceServer interface {
	GetSoChiTietVatLieu(*SoChiTietVatLieuRequest, grpc.ServerStreamingServer[SoChiTietVatLieuRow]) error
	mustEmbedUnimplementedSoChiTietVatLieuServiceServer()
}

// UnimplementedSoChiTietVatLieuServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSoChiTietVatLieuServiceServer struct{}

func (UnimplementedSoChiTietVatLieuServiceServer) GetSoChiTietVatLieu(*SoChiTietVatLieuRequest, grpc.ServerStreamingServer[SoChiTietVatLieuRow]) error {
	return status.Error(codes.Unimplemented, "method GetSoChiTietVatLieu not implemented")
}
func (UnimplementedSoChiTietVatLieuServiceServer) mustEmbedUnimplementedSoChiTietVatLieuServiceServer() {
}
func (UnimplementedSoChiTietVatLieuServiceServer) testEmbeddedByValue() {}

// UnsafeSoChiTietVatLieuServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SoChiTietVatLieuServiceServer will
// result in compilation errors.
type UnsafeSoChiTietVatLieuServiceServer interface {
	mustEmbedUnimplementedSoChiTietVatLieuServiceServer()
}

func RegisterSoChiTietVatLieuServiceServer(s grpc.ServiceRegistrar, srv SoChiTietVatLieuServiceServer) {
	// If the following call panics, it indicates UnimplementedSoChiTietVatLieuServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SoChiTietVatLieuService_ServiceDesc, srv)
}

func _SoChiTietVatLieuService_GetSoChiTietVatLieu_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SoChiTietVatLieuRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SoChiTietVatLieuServiceServer).GetSoChiTietVatLieu(m, &grpc.GenericServerStream[SoChiTietVatLieuRequest, SoChiTietVatLieuRow]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SoChiTietVatLieuService_GetSoChiTietVatLieuServer = grpc.ServerStreamingServer[SoChiTietVatLieuRow]

// SoChiTietVatLieuService_ServiceDesc is the grpc.ServiceDesc for SoChiTietVatLieuService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SoChiTietVatLieuService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sochitietvatlieu.SoChiTietVatLieuService",
	HandlerType: (*SoChiTietVatLieuServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetSoChiTietVatLieu",
			Handler:       _SoChiTietVatLieuService_GetSoChiTietVatLieu_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sochitietvatlieu.proto",
}
