// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: sochitietvatlieu.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SoChiTietVatLieuRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	CompanyIds               []string               `protobuf:"bytes,1,rep,name=company_ids,json=companyIds,proto3" json:"company_ids,omitempty"`
	PrimaryCompanyId         string                 `protobuf:"bytes,2,opt,name=primary_company_id,json=primaryCompanyId,proto3" json:"primary_company_id,omitempty"`
	RepositoryIds            []string               `protobuf:"bytes,3,rep,name=repository_ids,json=repositoryIds,proto3" json:"repository_ids,omitempty"`
	MaterialGoodsIds         []string               `protobuf:"bytes,4,rep,name=material_goods_ids,json=materialGoodsIds,proto3" json:"material_goods_ids,omitempty"`
	OwnRepositoryIds         []string               `protobuf:"bytes,5,rep,name=own_repository_ids,json=ownRepositoryIds,proto3" json:"own_repository_ids,omitempty"`
	OtherRepositoryIds       []string               `protobuf:"bytes,6,rep,name=other_repository_ids,json=otherRepositoryIds,proto3" json:"other_repository_ids,omitempty"`
	IsCompanyBusinessTypeGas int32                  `protobuf:"varint,7,opt,name=is_company_business_type_gas,json=isCompanyBusinessTypeGas,proto3" json:"is_company_business_type_gas,omitempty"`
	FromDate                 string                 `protobuf:"bytes,8,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"` // "2026-01-01 00:00:00"
	ToDate                   string                 `protobuf:"bytes,9,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`
	UnitType                 int32                  `protobuf:"varint,10,opt,name=unit_type,json=unitType,proto3" json:"unit_type,omitempty"`
	MaterialGoodsCategoryId  string                 `protobuf:"bytes,11,opt,name=material_goods_category_id,json=materialGoodsCategoryId,proto3" json:"material_goods_category_id,omitempty"` // "00000000-..." = khong loc
	GetAccountHasData        bool                   `protobuf:"varint,12,opt,name=get_account_has_data,json=getAccountHasData,proto3" json:"get_account_has_data,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *SoChiTietVatLieuRequest) Reset() {
	*x = SoChiTietVatLieuRequest{}
	mi := &file_sochitietvatlieu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SoChiTietVatLieuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoChiTietVatLieuRequest) ProtoMessage() {}

func (x *SoChiTietVatLieuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sochitietvatlieu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoChiTietVatLieuRequest.ProtoReflect.Descriptor instead.
func (*SoChiTietVatLieuRequest) Descriptor() ([]byte, []int) {
	return file_sochitietvatlieu_proto_rawDescGZIP(), []int{0}
}

func (x *SoChiTietVatLieuRequest) GetCompanyIds() []string {
	if x != nil {
		return x.CompanyIds
	}
	return nil
}

func (x *SoChiTietVatLieuRequest) GetPrimaryCompanyId() string {
	if x != nil {
		return x.PrimaryCompanyId
	}
	return ""
}

func (x *SoChiTietVatLieuRequest) GetRepositoryIds() []string {
	if x != nil {
		return x.RepositoryIds
	}
	return nil
}

func (x *SoChiTietVatLieuRequest) GetMaterialGoodsIds() []string {
	if x != nil {
		return x.MaterialGoodsIds
	}
	return nil
}

func (x *SoChiTietVatLieuRequest) GetOwnRepositoryIds() []string {
	if x != nil {
		return x.OwnRepositoryIds
	}
	return nil
}

func (x *SoChiTietVatLieuRequest) GetOtherRepositoryIds() []string {
	if x != nil {
		return x.OtherRepositoryIds
	}
	return nil
}

func (x *SoChiTietVatLieuRequest) GetIsCompanyBusinessTypeGas() int32 {
	if x != nil {
		return x.IsCompanyBusinessTypeGas
	}
	return 0
}

func (x *SoChiTietVatLieuRequest) GetFromDate() string {
	if x != nil {
		return x.FromDate
	}
	return ""
}

func (x *SoChiTietVatLieuRequest) GetToDate() string {
	if x != nil {
		return x.ToDate
	}
	return ""
}

func (x *SoChiTietVatLieuRequest) GetUnitType() int32 {
	if x != nil {
		return x.UnitType
	}
	return 0
}

func (x *SoChiTietVatLieuRequest) GetMaterialGoodsCategoryId() string {
	if x != nil {
		return x.MaterialGoodsCategoryId
	}
	return ""
}

func (x *SoChiTietVatLieuRequest) GetGetAccountHasData() bool {
	if x != nil {
		return x.GetAccountHasData
	}
	return false
}

// Cac field so lieu (quantity/amount/price) dung STRING, KHONG dung
// float/double - Protobuf khong co kieu Decimal native, dung float se MAT
// DO CHINH XAC voi so tien (da rut kinh nghiem tu decimal.Decimal xuyen
// suot du an nay). Ben nhan (Java) tu parse BigDecimal tu string.
type SoChiTietVatLieuRow struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	IsDetail                bool                   `protobuf:"varint,1,opt,name=is_detail,json=isDetail,proto3" json:"is_detail,omitempty"`
	RepositoryId            string                 `protobuf:"bytes,2,opt,name=repository_id,json=repositoryId,proto3" json:"repository_id,omitempty"`
	RepositoryCode          string                 `protobuf:"bytes,3,opt,name=repository_code,json=repositoryCode,proto3" json:"repository_code,omitempty"`
	RepositoryName          string                 `protobuf:"bytes,4,opt,name=repository_name,json=repositoryName,proto3" json:"repository_name,omitempty"`
	MaterialGoodsId         string                 `protobuf:"bytes,5,opt,name=material_goods_id,json=materialGoodsId,proto3" json:"material_goods_id,omitempty"`
	MaterialGoodsCode       string                 `protobuf:"bytes,6,opt,name=material_goods_code,json=materialGoodsCode,proto3" json:"material_goods_code,omitempty"`
	MaterialGoodsName       string                 `protobuf:"bytes,7,opt,name=material_goods_name,json=materialGoodsName,proto3" json:"material_goods_name,omitempty"`
	ReferenceId             string                 `protobuf:"bytes,8,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	DetailId                string                 `protobuf:"bytes,9,opt,name=detail_id,json=detailId,proto3" json:"detail_id,omitempty"`
	TypeId                  int32                  `protobuf:"varint,10,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	PostedDate              string                 `protobuf:"bytes,11,opt,name=posted_date,json=postedDate,proto3" json:"posted_date,omitempty"` // ISO8601
	RefDate                 string                 `protobuf:"bytes,12,opt,name=ref_date,json=refDate,proto3" json:"ref_date,omitempty"`          // rong "" neu la dong opening (NULL trong CH)
	RefNo                   string                 `protobuf:"bytes,13,opt,name=ref_no,json=refNo,proto3" json:"ref_no,omitempty"`
	Reason                  string                 `protobuf:"bytes,14,opt,name=reason,proto3" json:"reason,omitempty"`
	AccountCorresponding    string                 `protobuf:"bytes,15,opt,name=account_corresponding,json=accountCorresponding,proto3" json:"account_corresponding,omitempty"`
	CurrencyId              string                 `protobuf:"bytes,16,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`
	UnitId                  string                 `protobuf:"bytes,17,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`
	UnitName                string                 `protobuf:"bytes,18,opt,name=unit_name,json=unitName,proto3" json:"unit_name,omitempty"`
	ConvertRate             string                 `protobuf:"bytes,19,opt,name=convert_rate,json=convertRate,proto3" json:"convert_rate,omitempty"`
	MainQuantity            string                 `protobuf:"bytes,20,opt,name=main_quantity,json=mainQuantity,proto3" json:"main_quantity,omitempty"`
	MainUnitPrice           string                 `protobuf:"bytes,21,opt,name=main_unit_price,json=mainUnitPrice,proto3" json:"main_unit_price,omitempty"`
	UnitPrice               string                 `protobuf:"bytes,22,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	InwardQuantity          string                 `protobuf:"bytes,23,opt,name=inward_quantity,json=inwardQuantity,proto3" json:"inward_quantity,omitempty"`
	InwardAmount            string                 `protobuf:"bytes,24,opt,name=inward_amount,json=inwardAmount,proto3" json:"inward_amount,omitempty"`
	OutwardQuantity         string                 `protobuf:"bytes,25,opt,name=outward_quantity,json=outwardQuantity,proto3" json:"outward_quantity,omitempty"`
	OutwardAmount           string                 `protobuf:"bytes,26,opt,name=outward_amount,json=outwardAmount,proto3" json:"outward_amount,omitempty"`
	ClosingQuantity         string                 `protobuf:"bytes,27,opt,name=closing_quantity,json=closingQuantity,proto3" json:"closing_quantity,omitempty"`
	ClosingAmount           string                 `protobuf:"bytes,28,opt,name=closing_amount,json=closingAmount,proto3" json:"closing_amount,omitempty"`
	AccountingObjectId      string                 `protobuf:"bytes,29,opt,name=accounting_object_id,json=accountingObjectId,proto3" json:"accounting_object_id,omitempty"`
	AccountingObjectCode    string                 `protobuf:"bytes,30,opt,name=accounting_object_code,json=accountingObjectCode,proto3" json:"accounting_object_code,omitempty"`
	AccountingObjectName    string                 `protobuf:"bytes,31,opt,name=accounting_object_name,json=accountingObjectName,proto3" json:"accounting_object_name,omitempty"`
	AccountingObjectAddress string                 `protobuf:"bytes,32,opt,name=accounting_object_address,json=accountingObjectAddress,proto3" json:"accounting_object_address,omitempty"`
	TaxCode                 string                 `protobuf:"bytes,33,opt,name=tax_code,json=taxCode,proto3" json:"tax_code,omitempty"`
	ExpenseItemId           string                 `protobuf:"bytes,34,opt,name=expense_item_id,json=expenseItemId,proto3" json:"expense_item_id,omitempty"`
	ExpenseItemCode         string                 `protobuf:"bytes,35,opt,name=expense_item_code,json=expenseItemCode,proto3" json:"expense_item_code,omitempty"`
	ExpenseItemName         string                 `protobuf:"bytes,36,opt,name=expense_item_name,json=expenseItemName,proto3" json:"expense_item_name,omitempty"`
	BudgetItemId            string                 `protobuf:"bytes,37,opt,name=budget_item_id,json=budgetItemId,proto3" json:"budget_item_id,omitempty"`
	BudgetItemCode          string                 `protobuf:"bytes,38,opt,name=budget_item_code,json=budgetItemCode,proto3" json:"budget_item_code,omitempty"`
	BudgetItemName          string                 `protobuf:"bytes,39,opt,name=budget_item_name,json=budgetItemName,proto3" json:"budget_item_name,omitempty"`
	DepartmentId            string                 `protobuf:"bytes,40,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	OrganizationUnitCode    string                 `protobuf:"bytes,41,opt,name=organization_unit_code,json=organizationUnitCode,proto3" json:"organization_unit_code,omitempty"`
	OrganizationUnitName    string                 `protobuf:"bytes,42,opt,name=organization_unit_name,json=organizationUnitName,proto3" json:"organization_unit_name,omitempty"`
	CostSetId               string                 `protobuf:"bytes,43,opt,name=cost_set_id,json=costSetId,proto3" json:"cost_set_id,omitempty"`
	CostSetCode             string                 `protobuf:"bytes,44,opt,name=cost_set_code,json=costSetCode,proto3" json:"cost_set_code,omitempty"`
	CostSetName             string                 `protobuf:"bytes,45,opt,name=cost_set_name,json=costSetName,proto3" json:"cost_set_name,omitempty"`
	EmContractId            string                 `protobuf:"bytes,46,opt,name=em_contract_id,json=emContractId,proto3" json:"em_contract_id,omitempty"`
	ContractNo              string                 `protobuf:"bytes,47,opt,name=contract_no,json=contractNo,proto3" json:"contract_no,omitempty"`
	StatisticsCodeId        string                 `protobuf:"bytes,48,opt,name=statistics_code_id,json=statisticsCodeId,proto3" json:"statistics_code_id,omitempty"`
	StatisticsCode          string                 `protobuf:"bytes,49,opt,name=statistics_code,json=statisticsCode,proto3" json:"statistics_code,omitempty"`
	StatisticsCodeName      string                 `protobuf:"bytes,50,opt,name=statistics_code_name,json=statisticsCodeName,proto3" json:"statistics_code_name,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *SoChiTietVatLieuRow) Reset() {
	*x = SoChiTietVatLieuRow{}
	mi := &file_sochitietvatlieu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SoChiTietVatLieuRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoChiTietVatLieuRow) ProtoMessage() {}

func (x *SoChiTietVatLieuRow) ProtoReflect() protoreflect.Message {
	mi := &file_sochitietvatlieu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoChiTietVatLieuRow.ProtoReflect.Descriptor instead.
func (*SoChiTietVatLieuRow) Descriptor() ([]byte, []int) {
	return file_sochitietvatlieu_proto_rawDescGZIP(), []int{1}
}

func (x *SoChiTietVatLieuRow) GetIsDetail() bool {
	if x != nil {
		return x.IsDetail
	}
	return false
}

func (x *SoChiTietVatLieuRow) GetRepositoryId() string {
	if x != nil {
		return x.RepositoryId
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetRepositoryCode() string {
	if x != nil {
		return x.RepositoryCode
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetRepositoryName() string {
	if x != nil {
		return x.RepositoryName
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetMaterialGoodsId() string {
	if x != nil {
		return x.MaterialGoodsId
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetMaterialGoodsCode() string {
	if x != nil {
		return x.MaterialGoodsCode
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetMaterialGoodsName() string {
	if x != nil {
		return x.MaterialGoodsName
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetDetailId() string {
	if x != nil {
		return x.DetailId
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetTypeId() int32 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

func (x *SoChiTietVatLieuRow) GetPostedDate() string {
	if x != nil {
		return x.PostedDate
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetRefDate() string {
	if x != nil {
		return x.RefDate
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetRefNo() string {
	if x != nil {
		return x.RefNo
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetAccountCorresponding() string {
	if x != nil {
		return x.AccountCorresponding
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetCurrencyId() string {
	if x != nil {
		return x.CurrencyId
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetUnitName() string {
	if x != nil {
		return x.UnitName
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetConvertRate() string {
	if x != nil {
		return x.ConvertRate
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetMainQuantity() string {
	if x != nil {
		return x.MainQuantity
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetMainUnitPrice() string {
	if x != nil {
		return x.MainUnitPrice
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetUnitPrice() string {
	if x != nil {
		return x.UnitPrice
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetInwardQuantity() string {
	if x != nil {
		return x.InwardQuantity
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetInwardAmount() string {
	if x != nil {
		return x.InwardAmount
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetOutwardQuantity() string {
	if x != nil {
		return x.OutwardQuantity
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetOutwardAmount() string {
	if x != nil {
		return x.OutwardAmount
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetClosingQuantity() string {
	if x != nil {
		return x.ClosingQuantity
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetClosingAmount() string {
	if x != nil {
		return x.ClosingAmount
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetAccountingObjectId() string {
	if x != nil {
		return x.AccountingObjectId
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetAccountingObjectCode() string {
	if x != nil {
		return x.AccountingObjectCode
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetAccountingObjectName() string {
	if x != nil {
		return x.AccountingObjectName
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetAccountingObjectAddress() string {
	if x != nil {
		return x.AccountingObjectAddress
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetTaxCode() string {
	if x != nil {
		return x.TaxCode
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetExpenseItemId() string {
	if x != nil {
		return x.ExpenseItemId
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetExpenseItemCode() string {
	if x != nil {
		return x.ExpenseItemCode
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetExpenseItemName() string {
	if x != nil {
		return x.ExpenseItemName
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetBudgetItemId() string {
	if x != nil {
		return x.BudgetItemId
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetBudgetItemCode() string {
	if x != nil {
		return x.BudgetItemCode
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetBudgetItemName() string {
	if x != nil {
		return x.BudgetItemName
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetOrganizationUnitCode() string {
	if x != nil {
		return x.OrganizationUnitCode
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetOrganizationUnitName() string {
	if x != nil {
		return x.OrganizationUnitName
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetCostSetId() string {
	if x != nil {
		return x.CostSetId
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetCostSetCode() string {
	if x != nil {
		return x.CostSetCode
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetCostSetName() string {
	if x != nil {
		return x.CostSetName
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetEmContractId() string {
	if x != nil {
		return x.EmContractId
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetContractNo() string {
	if x != nil {
		return x.ContractNo
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetStatisticsCodeId() string {
	if x != nil {
		return x.StatisticsCodeId
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetStatisticsCode() string {
	if x != nil {
		return x.StatisticsCode
	}
	return ""
}

func (x *SoChiTietVatLieuRow) GetStatisticsCodeName() string {
	if x != nil {
		return x.StatisticsCodeName
	}
	return ""
}

var File_sochitietvatlieu_proto protoreflect.FileDescriptor

const file_sochitietvatlieu_proto_rawDesc = "" +
	"\n" +
	"\x16sochitietvatlieu.proto\x12\x10sochitietvatlieu\"\x9e\x04\n" +
	"\x17SoChiTietVatLieuRequest\x12\x1f\n" +
	"\vcompany_ids\x18\x01 \x03(\tR\n" +
	"companyIds\x12,\n" +
	"\x12primary_company_id\x18\x02 \x01(\tR\x10primaryCompanyId\x12%\n" +
	"\x0erepository_ids\x18\x03 \x03(\tR\rrepositoryIds\x12,\n" +
	"\x12material_goods_ids\x18\x04 \x03(\tR\x10materialGoodsIds\x12,\n" +
	"\x12own_repository_ids\x18\x05 \x03(\tR\x10ownRepositoryIds\x120\n" +
	"\x14other_repository_ids\x18\x06 \x03(\tR\x12otherRepositoryIds\x12>\n" +
	"\x1cis_company_business_type_gas\x18\a \x01(\x05R\x18isCompanyBusinessTypeGas\x12\x1b\n" +
	"\tfrom_date\x18\b \x01(\tR\bfromDate\x12\x17\n" +
	"\ato_date\x18\t \x01(\tR\x06toDate\x12\x1b\n" +
	"\tunit_type\x18\n" +
	" \x01(\x05R\bunitType\x12;\n" +
	"\x1amaterial_goods_category_id\x18\v \x01(\tR\x17materialGoodsCategoryId\x12/\n" +
	"\x14get_account_has_data\x18\f \x01(\bR\x11getAccountHasData\"\xbe\x0f\n" +
	"\x13SoChiTietVatLieuRow\x12\x1b\n" +
	"\tis_detail\x18\x01 \x01(\bR\bisDetail\x12#\n" +
	"\rrepository_id\x18\x02 \x01(\tR\frepositoryId\x12'\n" +
	"\x0frepository_code\x18\x03 \x01(\tR\x0erepositoryCode\x12'\n" +
	"\x0frepository_name\x18\x04 \x01(\tR\x0erepositoryName\x12*\n" +
	"\x11material_goods_id\x18\x05 \x01(\tR\x0fmaterialGoodsId\x12.\n" +
	"\x13material_goods_code\x18\x06 \x01(\tR\x11materialGoodsCode\x12.\n" +
	"\x13material_goods_name\x18\a \x01(\tR\x11materialGoodsName\x12!\n" +
	"\freference_id\x18\b \x01(\tR\vreferenceId\x12\x1b\n" +
	"\tdetail_id\x18\t \x01(\tR\bdetailId\x12\x17\n" +
	"\atype_id\x18\n" +
	" \x01(\x05R\x06typeId\x12\x1f\n" +
	"\vposted_date\x18\v \x01(\tR\n" +
	"postedDate\x12\x19\n" +
	"\bref_date\x18\f \x01(\tR\arefDate\x12\x15\n" +
	"\x06ref_no\x18\r \x01(\tR\x05refNo\x12\x16\n" +
	"\x06reason\x18\x0e \x01(\tR\x06reason\x123\n" +
	"\x15account_corresponding\x18\x0f \x01(\tR\x14accountCorresponding\x12\x1f\n" +
	"\vcurrency_id\x18\x10 \x01(\tR\n" +
	"currencyId\x12\x17\n" +
	"\aunit_id\x18\x11 \x01(\tR\x06unitId\x12\x1b\n" +
	"\tunit_name\x18\x12 \x01(\tR\bunitName\x12!\n" +
	"\fconvert_rate\x18\x13 \x01(\tR\vconvertRate\x12#\n" +
	"\rmain_quantity\x18\x14 \x01(\tR\fmainQuantity\x12&\n" +
	"\x0fmain_unit_price\x18\x15 \x01(\tR\rmainUnitPrice\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x16 \x01(\tR\tunitPrice\x12'\n" +
	"\x0finward_quantity\x18\x17 \x01(\tR\x0einwardQuantity\x12#\n" +
	"\rinward_amount\x18\x18 \x01(\tR\finwardAmount\x12)\n" +
	"\x10outward_quantity\x18\x19 \x01(\tR\x0foutwardQuantity\x12%\n" +
	"\x0eoutward_amount\x18\x1a \x01(\tR\routwardAmount\x12)\n" +
	"\x10closing_quantity\x18\x1b \x01(\tR\x0fclosingQuantity\x12%\n" +
	"\x0eclosing_amount\x18\x1c \x01(\tR\rclosingAmount\x120\n" +
	"\x14accounting_object_id\x18\x1d \x01(\tR\x12accountingObjectId\x124\n" +
	"\x16accounting_object_code\x18\x1e \x01(\tR\x14accountingObjectCode\x124\n" +
	"\x16accounting_object_name\x18\x1f \x01(\tR\x14accountingObjectName\x12:\n" +
	"\x19accounting_object_address\x18  \x01(\tR\x17accountingObjectAddress\x12\x19\n" +
	"\btax_code\x18! \x01(\tR\ataxCode\x12&\n" +
	"\x0fexpense_item_id\x18\" \x01(\tR\rexpenseItemId\x12*\n" +
	"\x11expense_item_code\x18# \x01(\tR\x0fexpenseItemCode\x12*\n" +
	"\x11expense_item_name\x18$ \x01(\tR\x0fexpenseItemName\x12$\n" +
	"\x0ebudget_item_id\x18% \x01(\tR\fbudgetItemId\x12(\n" +
	"\x10budget_item_code\x18& \x01(\tR\x0ebudgetItemCode\x12(\n" +
	"\x10budget_item_name\x18' \x01(\tR\x0ebudgetItemName\x12#\n" +
	"\rdepartment_id\x18( \x01(\tR\fdepartmentId\x124\n" +
	"\x16organization_unit_code\x18) \x01(\tR\x14organizationUnitCode\x124\n" +
	"\x16organization_unit_name\x18* \x01(\tR\x14organizationUnitName\x12\x1e\n" +
	"\vcost_set_id\x18+ \x01(\tR\tcostSetId\x12\"\n" +
	"\rcost_set_code\x18, \x01(\tR\vcostSetCode\x12\"\n" +
	"\rcost_set_name\x18- \x01(\tR\vcostSetName\x12$\n" +
	"\x0eem_contract_id\x18. \x01(\tR\femContractId\x12\x1f\n" +
	"\vcontract_no\x18/ \x01(\tR\n" +
	"contractNo\x12,\n" +
	"\x12statistics_code_id\x180 \x01(\tR\x10statisticsCodeId\x12'\n" +
	"\x0fstatistics_code\x181 \x01(\tR\x0estatisticsCode\x120\n" +
	"\x14statistics_code_name\x182 \x01(\tR\x12statisticsCodeName2\x84\x01\n" +
	"\x17SoChiTietVatLieuService\x12i\n" +
	"\x13GetSoChiTietVatLieu\x12).sochitietvatlieu.SoChiTietVatLieuRequest\x1a%.sochitietvatlieu.SoChiTietVatLieuRow0\x01B\x86\x01\n" +
	"%vn.softdream.reports.sochitietvatlieuB\x15SoChiTietVatLieuProtoP\x01ZDsoftdream.vn/go-gateway/internal/so_chi_tiet_vat_lieu_hang_hoa/pb;pbb\x06proto3"

var (
	file_sochitietvatlieu_proto_rawDescOnce sync.Once
	file_sochitietvatlieu_proto_rawDescData []byte
)

func file_sochitietvatlieu_proto_rawDescGZIP() []byte {
	file_sochitietvatlieu_proto_rawDescOnce.Do(func() {
		file_sochitietvatlieu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sochitietvatlieu_proto_rawDesc), len(file_sochitietvatlieu_proto_rawDesc)))
	})
	return file_sochitietvatlieu_proto_rawDescData
}

var file_sochitietvatlieu_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sochitietvatlieu_proto_goTypes = []any{
	(*SoChiTietVatLieuRequest)(nil), // 0: sochitietvatlieu.SoChiTietVatLieuRequest
	(*SoChiTietVatLieuRow)(nil),     // 1: sochitietvatlieu.SoChiTietVatLieuRow
}
var file_sochitietvatlieu_proto_depIdxs = []int32{
	0, // 0: sochitietvatlieu.SoChiTietVatLieuService.GetSoChiTietVatLieu:input_type -> sochitietvatlieu.SoChiTietVatLieuRequest
	1, // 1: sochitietvatlieu.SoChiTietVatLieuService.GetSoChiTietVatLieu:output_type -> sochitietvatlieu.SoChiTietVatLieuRow
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sochitietvatlieu_proto_init() }
func file_sochitietvatlieu_proto_init() {
	if File_sochitietvatlieu_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sochitietvatlieu_proto_rawDesc), len(file_sochitietvatlieu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sochitietvatlieu_proto_goTypes,
		DependencyIndexes: file_sochitietvatlieu_proto_depIdxs,
		MessageInfos:      file_sochitietvatlieu_proto_msgTypes,
	}.Build()
	File_sochitietvatlieu_proto = out.File
	file_sochitietvatlieu_proto_goTypes = nil
	file_sochitietvatlieu_proto_depIdxs = nil
}
